<?php

namespace AppBundle\Repository;

/**
 * AttributiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributiRepository extends \Doctrine\ORM\EntityRepository
{
}
