<?php

namespace AppBundle\Repository;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{
     public function RicercaSottoCategorie($em,$padre){
        
        
        $query = $em->createQuery(
            'SELECT count(c.id)
            FROM AppBundle:Categoria c
            WHERE c.categoriaPadreId= :str ' 
        )->setParameter('str',$padre);
        
        $nris=$query->getSingleScalarResult();
        if($nris==0){
            return 0;
        
        } else {
            $query = $em->createQuery(
            'SELECT c.nome, c.descrizione, c.id, c.immagine
            FROM AppBundle:Categoria c
            WHERE c.categoriaPadreId= :str ' 
        )->setParameter('str',$padre);
        
        }
        $ris = $query->getResult();
        return $ris;
    }
}
