<?php

namespace AppBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
    public function creaCliente($session){
        $cliente = new \AppBundle\Entity\Cliente();
        $cliente->setNome($session->get('nome'));
        $cliente->setCognome($session->get('cognome'));
        $data = \DateTime::createFromFormat('Y-m-d', $session->get('data_nascita') );
        $cliente->setDataNascita($data);
        $cliente->setCodiceFiscale($session->get('codice_fiscale'));
        $cliente->setTelefono($session->get('telefono'));
        $cliente->setVia($session->get('via'));
        $cliente->setNumeroCivico($session->get('numero'));
        $cliente->setCitta($session->get('citta'));
        $cliente->setCAP($session->get('cap'));
        $cliente->setUsername($session->get('username'));
        $cliente->setPassword("ciaociao");//password dovrà essere generata in modo random
        $cliente->setMail($session->get('mail'));
        $cliente->setNote($session->get('note'));
        $cliente->setFax($session->get('fax'));
        return($cliente);
    }
    
    public function RicercaFulltext($em,$str){
        $query = $em->createQuery(
            'SELECT c.nome as nome, c.cognome, c.id as codicecliente, c.codiceFiscale, c.mail
            FROM AppBundle:Cliente c
            WHERE c.nome like :str or c.cognome like :str or c.mail LIKE :str or c.username LIKE :str or c.id like :str or c.codiceFiscale like :str' 
        )->setParameter('str',$str);

        $ris = $query->setMaxResults(25)->getResult();
        return $ris;
    }
    
     public function RicercaClienteById($em,$id){
        $query = $em->createQuery(
            'SELECT c.nome as nome, c.cognome, c.id as codicecliente, c.codiceFiscale, c.mail, c.fax, c.telefono, c.via, c.numeroCivico, c.dataNascita, c.citta
            FROM AppBundle:Cliente c
            WHERE c.id=:id' 
        )->setParameter('id',$id);

        $ris = $query->getResult();
        return $ris;
    }
    
    
}
