<?php

namespace AppBundle\Repository;

/**
 * EventoRichiestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRichiestaRepository extends \Doctrine\ORM\EntityRepository
{
}
