<?php

namespace AppBundle\Repository;

/**
 * FaseProduzioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaseProduzioneRepository extends \Doctrine\ORM\EntityRepository
{
}
