<?php

namespace AppBundle\Repository;

/**
 * GraficaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraficaRepository extends \Doctrine\ORM\EntityRepository
{
}
