<?php

namespace AppBundle\Repository;

/**
 * GraficoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraficoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function checkUsername($em,$user){
        
        $p = $em->getRepository("AppBundle:Grafico")->findOneBy(array("username"=>$user,));
        if(!$p) {
            return(FALSE); //cos'è p
        }else {return TRUE;}
    }
    
    public function getIdByUsername($em,$user){
        $query = $em->createQuery(
            'SELECT g.id
            FROM AppBundle:Grafico g
            WHERE g.username = :user'
        )->setParameter('user', $user);
        return($query->getSingleScalarResult());
    }
    
    public function tabellaEseguire($em,$user,$n){
        
        $id= $this->getIdByUsername($em,$user);
        $query = $em->createQuery(
            'SELECT c.Nome, c.Cognome, o.id, o.Data
            FROM AppBundle:Grafica g, Appbundle:Ordine o, AppBundle:Cliente c
            WHERE g.GraficoId = :id AND e.Tipo= ?' 
        )->setParameter(1, 'Da Assegnare', 'id',$id);

        $tabellaEseguire = $query->setMaxResults($n)->getResult();
        return $tabellaEseguire;

    }
    
    public function tabellaInLavorazione($em, $user, $n){
        
        $id= $this->getIdByUsername($em,$user);
        $query = $em->createQuery(
            'SELECT c.Nome, c.Cognome, o.id, o.Data
            FROM AppBundle:Grafica g, Appbundle:Ordine o, AppBundle:Cliente c
            WHERE g.GraficoId = :id AND e.Tipo= ?' 
        )->setParameter(1, 'In Lavorazione', 'id',$id);
        
        $tabellaLavorazione = $query->setMaxResults($n)->getResult();
        return $tabellaLavorazione;

    }
    
    public function tabellaDaRieseguire ($em, $user, $id){
        
        
    }

}
 
 