<?php

namespace AppBundle\Repository;

/**
 * GruppoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GruppoRepository extends \Doctrine\ORM\EntityRepository
{
}
