<?php

namespace AppBundle\Repository;

/**
 * Gruppo_AttributiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Gruppo_AttributiRepository extends \Doctrine\ORM\EntityRepository
{
}
