<?php

namespace AppBundle\Repository;

/**
 * OperatoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatoreRepository extends \Doctrine\ORM\EntityRepository
{
}
