<?php

namespace AppBundle\Repository;

/**
 * PossedereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PossedereRepository extends \Doctrine\ORM\EntityRepository
{
}
