<?php

namespace AppBundle\Repository;

/**
 * ProdurreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdurreRepository extends \Doctrine\ORM\EntityRepository
{
}
