<?php

namespace AppBundle\Repository;

/**
 * ProducibileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducibileRepository extends \Doctrine\ORM\EntityRepository
{
}
