<?php

namespace AppBundle\Repository;

/**
 * SitoProduzioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitoProduzioneRepository extends \Doctrine\ORM\EntityRepository
{
}
