<?php

namespace AppBundle\Repository;

/**
 * StatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatoRepository extends \Doctrine\ORM\EntityRepository
{
}
