<?php

namespace AppBundle\Repository;

/**
 * StatoProduzioneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatoProduzioneRepository extends \Doctrine\ORM\EntityRepository
{
}
