<?php

namespace AppBundle\Repository;

/**
 * StudioGraficoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudioGraficoRepository extends \Doctrine\ORM\EntityRepository
{
}
