<?php

namespace AppBundle\Repository;

/**
 * Valori_ArticoloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Valori_ArticoloRepository extends \Doctrine\ORM\EntityRepository
{
}
