<?php

namespace AppBundle\Repository;

/**
 * ValoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoreRepository extends \Doctrine\ORM\EntityRepository
{
     public function RicercaValoriByAttributo($em,$str){
        $query = $em->createQuery(
            'SELECT v.id as idvalore,v.nome as valore
            FROM AppBundle:Valore v
            WHERE v.attributoId=:str' 
        )->setParameter('str',$str);

        $ris = $query->setMaxResults(25)->getResult();
        return $ris;
    }
}
